// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ymltekstil.IdeaSoft.Server.Database;

namespace Ymltekstil.IdeaSoft.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210304065400_RefreshToken")]
    partial class RefreshToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ymltekstil.IdeaSoft.Server.Database.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c13c7c5d-d9cd-4a26-92a6-7b713ec8c48c"),
                            Key = "RefreshToken",
                            Value = "N2ViMWVmNDVjYzdjMzgzYjZiODFlOTc3YmVmNGQ5MTExMmNiOGQ0ODhiYjA0Y2Q1ODk2YTU0OTc5NGJlMzk5Mg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
